### ISSUE TITLE
集群中某个k8s节点重启会导致链码无法查询

### ISSUE THREAD

**Issue by marryton007** [hainingzhang/articles#3]
首先非常感谢大大的付出！

说明一下我的问题，使用4台ubuntu16.04 机器搭建好k8s后, 按照FabricOnK8SAll.pdf中的说明，一切正常，链部署，初始化，查询都是正常的。但当我重启其中某一台机器后，再去执行测试中的最后一步，查询链的状态时：

# 重启某一节点后再次查询
deploy@devops-server:~$ kubectl exec -it cli-594b5c4d54-hnrvw bash --namespace=org1
root@cli-594b5c4d54-hnrvw:/opt/gopath/src/github.com/hyperledger/fabric/peer#
peer chaincode query -C mychannel -n mycc -c '{"Args":["query","a"]}' 
2017-11-17 01:58:03.041 UTC [msp] GetLocalMSP -> DEBU 001 Returning existing local MSP
2017-11-17 01:58:03.041 UTC [msp] GetDefaultSigningIdentity -> DEBU 002 Obtaining default signing identity
2017-11-17 01:58:03.041 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 003 Using default escc
2017-11-17 01:58:03.041 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 004 Using default vscc
2017-11-17 01:58:03.041 UTC [msp/identity] Sign -> DEBU 005 Sign: plaintext: 0AE3060A6608031A0B08AB84B9D00510...6D7963631A0A0A0571756572790A0161
2017-11-17 01:58:03.041 UTC [msp/identity] Sign -> DEBU 006 Sign: digest: 35F21929076B5730B17A3FD5BF44AFDF661D7398920D7C52D9F635F34ACEC7EC
Error: Error endorsing query: rpc error: code = Unknown desc = Failed to deserialize creator identity, err MSP Org1MSP is unknown - <nil>
Usage:
  peer chaincode query [flags]

Flags:
  -C, --channelID string   The channel on which this command should be executed (default "testchainid")
  -c, --ctor string        Constructor message for the chaincode in JSON format (default "{}")
  -x, --hex                If true, output the query value byte array in hexadecimal. Incompatible with --raw
  -n, --name string        Name of the chaincode
  -r, --raw                If true, output the query value as raw bytes, otherwise format as a printable string
  -t, --tid string         Name of a custom ID generation algorithm (hashing and decoding) e.g. sha256base64

Global Flags:
      --cafile string              Path to file containing PEM-encoded trusted certificate(s) for the ordering endpoint
      --logging-level string       Default logging level and overrides, see core.yaml for full syntax
  -o, --orderer string             Ordering service endpoint
      --test.coverprofile string   Done (default "coverage.cov")
      --tls                        Use TLS when communicating with the orderer endpoint
  -v, --version                    Display current version of fabric peer server

root@cli-594b5c4d54-hnrvw:/opt/gopath/src/github.com/hyperledger/fabric/peer#

之后再重新执行前面的操作：新建通道，加入通道，安装/初始化链码，查询都是正常的。其表现看起来就像是整个链归零了一样。

**Comment by zhaopf2017** [comment]
数据没有持久化。需要为peer,orderer,couchdb建立持久化

**Comment by marryton007** [comment]
谢谢，这个问题已经解决了。
